name = "weather-website"
main = "_worker.js"
compatibility_date = "2023-06-12"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
name = "weather-website-prod"

[vars]
PORT = "8787" 