name = "weather-website"
main = "src/index.js"
compatibility_date = "2023-06-12"

[site]
bucket = "./public"

[build]
command = "npm run build"

[env.production]
name = "weather-website-prod"

[vars]
PORT = "8787" 