name = "weather-website"
main = "dist/worker.js"
type = "javascript"
compatibility_date = "2024-03-08"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"
include = ["index.html", "styles.css", "scripts.js"]

[build]
command = "npm run build"

[env.production]
name = "weather-website-prod"

[vars]
PORT = "8787"
WEATHER_API_KEY = "7e123ef793714185994205801250703" 